### ISSUE TITLE
Error with current OpenNLP Services at Brandeis

### ISSUE THREAD

**Issue by marcverhagen** [lappsgrid-services/edu.brandeis.cs.opennlp-web-service#7] opened 2017-06-08 20:14 UTC
This was exposed by clicking the metadata view button of an OpenNLP service at http://api.lappsgrid.org/services/brandeis, which gives you.

```
HTTP ERROR 500

Problem accessing /metadata. Reason:

    GroovyServlet Error:  script: '/metadata':  Script processing failed.
No such property: license for class: java.lang.Stringorg.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
```

This appears to be because the GroovyServlet pings the service and then Tomcat returns an error URL which then the GroovyServlet fails to parse because it expects LIF.

When pinging getMetaData() of opennlp-web-service#2.0.3 the catalina.out log in /local/eldrad/users/lapps/tomcat7/8282 shows

```

INFO  [OpenNLPAbstractWebService.loadModels:68] loadModels(): Creating OpenNLP ...
INFO  [OpenNLPAbstractWebService.loadModels:75] loadModels(): load opennlp-web-service.properties.
INFO  [OpenNLPAbstractWebService.loadPOSModel:185] loadModels(): load POSTAGGER MODEl "en-pos-maxent.bin"
ERROR [OpenNLPAbstractWebService.logAndThrowError:99] load(): fail to open POSTAGGER MODEL "en-pos-maxent.bin".
```  

The following file does exist on the server

```
~lapps/tomcat7/8282/webapps/opennlp-web-service#2.0.3/WEB-INF/classes/en-pos-maxent.bin
```

**Comment by keighrim** [comment] 2017-06-22 13:16
This has been issue for a long time. The quick fix is to turn off and on bask the services tomcat server (eldrad:8282). I spent a lot of time figuring out the cause of this fail-to-load error, but couldn't pinpoint the spot. In a broader sense, it must be some sort of memory issue of the server.

**Comment by ksuderman** [comment] 2019-02-22 00:04
Has this ever been resolved?  Can we close this issue?

FWIW I have 48G allocated to Tomcat.  I have also enabled heap dumps on OOM errors (-XX:+HeapDumpOnOutOfMemoryError).  In particular, I have the following in Tomcat's `bin/setenv.sh`:

```
CATALINA_OPTS="-server -Xmx48G -Xms48G -XX:PermSize=4G -XX:MaxPermSize=4G -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -XX:ParallelGCThreads=2 -XX:-UseConcMarkSweepGC -XX:-PrintGC -XX:-PrintGCDetails -XX:-PrintGCTimeStamps -XX:-TraceClassUnloading -XX:-TraceClassLoading"
```
If you are still getting OOM errors that are fixed by a Tomcat restart then I strongly suspect that the service is leaking memory.

**Comment by keighrim** [comment] 2019-02-26 21:22
Max was set to 48G. I gave startup memory 48G (`Xms`). Heap dump was also on. I gave much bigger `permGen`, from 512M to 4G. 
In fact, we've never experiences this OOM issue for a while, last instance in the log is actually from 2017 June. So I think we can close issue.

**Closed as completed by keighrim** 2019-02-26 21:22 UTC
Labels: wontfix
